substitutions:
  # Default values, can be overridden when submitting the build
  _REGION: us-central1
  _SERVICE_NAME: token-exchange
  _SECRET_NAME: token-exchange-private-key
steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$SHORT_SHA",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:latest",
        ".",
      ]

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}"]
    waitFor: ["Build"] # Ensure build is finished before pushing

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$SHORT_SHA",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--set-secrets=/secrets/jwk-priv.json=${_SECRET_NAME}:latest",
        "--set-env-vars=PROJECT_ID=${PROJECT_ID}",
        "--memory=256Mi",
        "--cpu=1",
        "--project=${PROJECT_ID}",
      ]
    waitFor: ["Push"]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:latest"
